import type { LocationPage } from "./types";

function localFaqs(city: string, localConcern: string) {
  return [
    { question: `Does Cool Fox provide HVAC service in ${city}?`, answer: `Yes. Cool Fox serves homes and businesses in ${city}, subject to daily scheduling and technician availability.` },
    { question: `What HVAC problems are common in ${city}?`, answer: localConcern },
    { question: `Is same-day service available in ${city}?`, answer: "Same-day appointments are available based on capacity and location. Call early for the best scheduling options." },
    { question: `Can I request emergency service in ${city}?`, answer: "Yes. Cool Fox offers 24/7 emergency HVAC service. Calling is the fastest way to reach the team for urgent help." },
  ];
}

const locationData: Omit<LocationPage, "faqs">[] = [
  {
    slug: "phoenix",
    city: "Phoenix",
    region: "Central Valley",
    introduction: "Phoenix cooling systems face long run times, intense rooftop heat, and heavy seasonal demand. Cool Fox brings practical repair and replacement guidance to homes and businesses across the city.",
    coverageNotes: "Service is available across central, north, and west Phoenix, with routing coordinated by daily technician coverage.",
    localConcern: "Long summer run times can expose weak capacitors, restricted airflow, dirty coils, aging compressors, and duct losses.",
    nearbyAreas: ["Glendale", "Scottsdale", "Tempe"],
  },
  {
    slug: "glendale",
    city: "Glendale",
    region: "West Valley",
    introduction: "Glendale homes range from established neighborhoods to newer communities, and their comfort needs are just as varied. We service common split systems, heat pumps, packaged units, and light commercial equipment.",
    coverageNotes: "Coverage includes central Glendale, Arrowhead, and nearby West Valley neighborhoods.",
    localConcern: "Older ductwork, attic heat, and aging rooftop equipment can contribute to uneven rooms and high cooling costs.",
    nearbyAreas: ["Phoenix", "Peoria", "Surprise"],
  },
  {
    slug: "peoria",
    city: "Peoria",
    region: "West Valley",
    introduction: "From established neighborhoods south of Bell Road to growing communities in north Peoria, reliable cooling depends on sound airflow, correct sizing, and careful maintenance.",
    coverageNotes: "Cool Fox schedules service throughout Peoria and coordinates northern calls with nearby New River routes.",
    localConcern: "Larger homes, long duct runs, and west-facing rooms often make airflow balance and equipment sizing especially important.",
    nearbyAreas: ["Glendale", "Surprise", "New River"],
  },
  {
    slug: "surprise",
    city: "Surprise",
    region: "West Valley",
    introduction: "Surprise residents need cooling that can handle long, dry summers without wasting energy. Cool Fox provides diagnosis, maintenance, and replacement options built around the property rather than a generic recommendation.",
    coverageNotes: "Service includes Surprise, Sun City area routes, and nearby West Valley communities when capacity allows.",
    localConcern: "Rapid development means homes may have very different equipment ages, filter setups, and builder duct designs even within the same area.",
    nearbyAreas: ["Peoria", "Glendale", "Goodyear"],
  },
  {
    slug: "goodyear",
    city: "Goodyear",
    region: "West Valley",
    introduction: "Goodyear homes and businesses rely on efficient cooling through months of high temperatures. We focus on clear diagnostics, strong airflow, and repair choices that make sense for the equipment condition.",
    coverageNotes: "Coverage spans central Goodyear, Estrella area routes, and adjacent communities based on the day schedule.",
    localConcern: "Dust, long cooling cycles, and large temperature swings can accelerate filter loading and expose marginal electrical components.",
    nearbyAreas: ["Avondale", "Buckeye", "Surprise"],
  },
  {
    slug: "avondale",
    city: "Avondale",
    region: "West Valley",
    introduction: "Avondale property owners can call Cool Fox for responsive residential and commercial heating and cooling care. We explain what failed, what can wait, and what work is worth considering now.",
    coverageNotes: "Avondale calls are commonly routed with Goodyear and west Phoenix service appointments.",
    localConcern: "High attic temperatures and heavy summer use can make small airflow or electrical problems become noticeable very quickly.",
    nearbyAreas: ["Goodyear", "Phoenix", "Buckeye"],
  },
  {
    slug: "buckeye",
    city: "Buckeye",
    region: "West Valley",
    introduction: "Buckeye is growing quickly, with comfort needs that range from new construction adjustments to repairs on hard-working existing systems. Cool Fox provides straightforward service for both.",
    coverageNotes: "Buckeye appointments are grouped by area to provide useful arrival windows across the expanding city.",
    localConcern: "Construction dust, long travel distances between neighborhoods, and exposed outdoor equipment make timely maintenance particularly useful.",
    nearbyAreas: ["Goodyear", "Avondale", "Surprise"],
  },
  {
    slug: "scottsdale",
    city: "Scottsdale",
    region: "East Valley",
    introduction: "Scottsdale comfort systems often combine multiple zones, high-efficiency equipment, and specific indoor air goals. Cool Fox starts with a complete assessment before suggesting changes.",
    coverageNotes: "Service is available in south, central, and north Scottsdale according to daily technician routing.",
    localConcern: "Multi-zone homes, large glass areas, and varied ceiling heights can make accurate airflow and load evaluation important.",
    nearbyAreas: ["Phoenix", "Tempe", "Mesa"],
  },
  {
    slug: "mesa",
    city: "Mesa",
    region: "East Valley",
    introduction: "Mesa has a wide mix of homes, small businesses, packaged units, split systems, and heat pumps. Cool Fox provides clear repair findings and practical paths forward.",
    coverageNotes: "Coverage extends across Mesa with eastern calls coordinated alongside Apache Junction routes.",
    localConcern: "A mix of older properties and newer developments means duct condition, electrical service, and equipment age can vary widely.",
    nearbyAreas: ["Tempe", "Chandler", "Apache Junction"],
  },
  {
    slug: "chandler",
    city: "Chandler",
    region: "East Valley",
    introduction: "Chandler homes and workplaces need dependable cooling and balanced airflow through peak summer. We service, maintain, and replace common residential and light commercial systems.",
    coverageNotes: "Chandler appointments are routed with nearby Tempe and Mesa service calls when practical.",
    localConcern: "Two-story layouts and long duct paths can make upstairs comfort, return airflow, and thermostat placement important diagnostic clues.",
    nearbyAreas: ["Tempe", "Mesa", "Scottsdale"],
  },
  {
    slug: "tempe",
    city: "Tempe",
    region: "East Valley",
    introduction: "Tempe includes older homes, renovated properties, rentals, and busy commercial spaces. Cool Fox adapts the service plan to the equipment, access, and property needs.",
    coverageNotes: "Service is available throughout Tempe, including calls coordinated with south Scottsdale and west Mesa.",
    localConcern: "Older ducts, compact mechanical spaces, and additions can create airflow and sizing challenges that require careful inspection.",
    nearbyAreas: ["Phoenix", "Scottsdale", "Mesa"],
  },
  {
    slug: "apache-junction",
    city: "Apache Junction",
    region: "East Valley",
    introduction: "Apache Junction heat, dust, and exposure place real demands on outdoor HVAC equipment. Cool Fox helps property owners keep systems clean, reliable, and ready for peak weather.",
    coverageNotes: "Appointments are scheduled in coordinated east Mesa and Apache Junction service windows.",
    localConcern: "Windblown dust and exposed condensers can reduce heat transfer and contribute to wear when equipment is not inspected regularly.",
    nearbyAreas: ["Mesa", "Chandler", "Scottsdale"],
  },
  {
    slug: "new-river",
    city: "New River",
    region: "North Valley",
    introduction: "New River properties often have more space, unique equipment access, and greater exposure to desert conditions. We ask the right scheduling questions and arrive prepared for the system type.",
    coverageNotes: "New River calls are grouped with north Phoenix and north Peoria routes to support reliable scheduling.",
    localConcern: "Distance, dust exposure, and package or split equipment variations make accurate model details helpful before the visit.",
    nearbyAreas: ["Phoenix", "Peoria", "Black Canyon City"],
  },
  {
    slug: "black-canyon-city",
    city: "Black Canyon City",
    region: "Northern Arizona",
    introduction: "Black Canyon City sits between Valley heat and cooler high-country nights. Cool Fox supports both cooling and heating needs with service planned for the local terrain and travel time.",
    coverageNotes: "Calls are scheduled in Northern Arizona route windows, so sharing system details in advance helps the team prepare.",
    localConcern: "Wider seasonal temperature changes mean both cooling and heating operation deserve attention during routine service.",
    nearbyAreas: ["New River", "Dewey-Humboldt", "Prescott Valley"],
  },
  {
    slug: "dewey-humboldt",
    city: "Dewey-Humboldt",
    region: "Northern Arizona",
    introduction: "Dewey-Humboldt properties experience hot afternoons, cool nights, and a true heating season. Cool Fox services heat pumps, furnaces, and cooling equipment with those changing conditions in mind.",
    coverageNotes: "Service is coordinated with Prescott Valley and nearby Northern Arizona routes.",
    localConcern: "Temperature swings and colder winters can reveal heat pump changeover, defrost, or backup heat issues that are less common in central Phoenix.",
    nearbyAreas: ["Prescott Valley", "Prescott", "Black Canyon City"],
  },
  {
    slug: "prescott-valley",
    city: "Prescott Valley",
    region: "Northern Arizona",
    introduction: "Prescott Valley needs year-round HVAC care, including dependable heating through colder months and efficient cooling during warm, sunny summers.",
    coverageNotes: "Local appointments are coordinated with Dewey-Humboldt and Prescott service routes.",
    localConcern: "Heat pump performance, overnight cold, dry air, and seasonal maintenance are frequent comfort considerations in this elevation.",
    nearbyAreas: ["Dewey-Humboldt", "Prescott", "Black Canyon City"],
  },
  {
    slug: "prescott",
    city: "Prescott",
    region: "Northern Arizona",
    introduction: "Prescott homes need reliable heating as well as summer cooling. Cool Fox provides honest repair and replacement guidance for equipment working across all four seasons.",
    coverageNotes: "Prescott service is scheduled with nearby Prescott Valley routes and confirmed according to technician availability.",
    localConcern: "Colder winter nights, older housing, and varied elevations make heating safety, duct condition, and correct system setup especially important.",
    nearbyAreas: ["Prescott Valley", "Dewey-Humboldt", "Black Canyon City"],
  },
];

export const locations: LocationPage[] = locationData.map((location) => ({
  ...location,
  faqs: localFaqs(location.city, location.localConcern),
}));

export function getLocation(slug: string) {
  return locations.find((location) => location.slug === slug);
}
