import type { ServicePage } from "./types";

const standardProcess = [
  { title: "Tell us what is happening", text: "Call or send a service request with the symptoms you have noticed." },
  { title: "We inspect the system", text: "A technician checks the equipment and explains the cause in plain language." },
  { title: "You choose the next step", text: "You receive clear options and pricing before work begins." },
  { title: "We complete and verify", text: "We finish the approved work, test operation, and leave the area clean." },
];

export const services: ServicePage[] = [
  {
    slug: "ac-repair",
    title: "AC Repair in Arizona",
    shortTitle: "AC Repair",
    summary: "Fast diagnosis and practical repairs that restore reliable cooling.",
    description: "When your air conditioner struggles in Arizona heat, Cool Fox finds the cause and gives you clear repair options without pressure.",
    symptoms: ["Warm air from vents", "Weak or uneven airflow", "Short cycling", "Unusual sounds or odors", "Water near the indoor unit", "Unexpected energy bill increases"],
    inclusions: ["Full system diagnosis", "Electrical and control checks", "Airflow and temperature testing", "Repair options with upfront pricing", "Post-repair performance verification"],
    process: standardProcess,
    faqs: [
      { question: "Why is my AC blowing warm air?", answer: "Common causes include a dirty filter, thermostat issue, frozen coil, electrical fault, or refrigerant problem. A proper diagnosis prevents unnecessary parts replacement." },
      { question: "What signs indicate an AC repair is needed?", answer: "Warm rooms, weak airflow, frequent cycling, new noises, moisture, odors, or a sudden increase in power use are good reasons to schedule an inspection." },
      { question: "How quickly can Cool Fox arrive?", answer: "Same-day service is available based on technician capacity and location. Call for the most accurate arrival window." },
      { question: "Do you service all brands?", answer: "Cool Fox services common residential and commercial HVAC brands. Share the model information when you schedule if you have it." },
      { question: "Should I repair or replace my system?", answer: "Age, repair cost, comfort, efficiency, and parts availability all matter. We explain both paths so you can choose what fits your home and budget." },
    ],
    relatedServices: ["maintenance-plans", "ac-installation", "emergency-hvac"],
    icon: "snowflake",
  },
  {
    slug: "ac-installation",
    title: "AC Installation and Replacement",
    shortTitle: "AC Installation",
    summary: "Right-sized cooling systems installed for dependable Arizona comfort.",
    description: "A quality installation starts with the right equipment and careful setup. We help you compare practical options for your property and comfort goals.",
    symptoms: ["System is near the end of its useful life", "Frequent or expensive repairs", "Persistent hot and cold rooms", "High cooling costs", "Major refrigerant or compressor failure"],
    inclusions: ["Home and comfort assessment", "Equipment sizing review", "Clear installation proposal", "Removal of replaced equipment", "Startup, testing, and owner walkthrough"],
    process: standardProcess,
    faqs: [
      { question: "What is included in an installation quote?", answer: "The proposal identifies the recommended system, installation scope, included materials, and total approved price. Any optional work is presented separately." },
      { question: "How long does an Arizona AC system normally last?", answer: "Many systems last about 10 to 15 years in Arizona, but maintenance, installation quality, usage, and exposure can change that range." },
      { question: "How is a new system sized?", answer: "Square footage alone is not enough. Construction, insulation, windows, orientation, ductwork, and comfort concerns should all inform equipment sizing." },
      { question: "Can I get a second opinion?", answer: "Yes. Cool Fox can review another diagnosis or replacement recommendation and explain the available options." },
    ],
    relatedServices: ["ac-repair", "mini-split-installation", "maintenance-plans"],
    icon: "unit",
  },
  {
    slug: "mini-split-installation",
    title: "Mini Split Installation for Arizona Homes",
    shortTitle: "Mini Split Installation",
    summary: "Targeted comfort for hot rooms, additions, garages, and spaces central ductwork cannot reach well.",
    description: "A ductless mini split can cool the exact room that needs help without replacing an otherwise dependable central system. Cool Fox evaluates the space, electrical needs, equipment location, and budget so you can compare a targeted solution with larger whole-home work.",
    symptoms: ["One room stays hotter than the rest", "A garage, workshop, or home office needs cooling", "A new addition has no practical duct connection", "The central system works but cannot balance a problem area", "You want room-by-room temperature control"],
    inclusions: ["Hot-spot and room load assessment", "Indoor and outdoor equipment placement plan", "Electrical and condensate routing review", "Clear equipment and installation proposal", "Startup, testing, and controls walkthrough"],
    process: standardProcess,
    faqs: [
      { question: "What spaces work well with a mini split?", answer: "Mini splits are often a strong fit for hot bedrooms, garages, workshops, home offices, additions, guest spaces, and rooms that are difficult to reach with existing ductwork." },
      { question: "Can a mini split cost less than replacing central AC?", answer: "Often, yes, when the comfort problem is limited to one or two spaces and the central system is still dependable. The total depends on capacity, electrical work, equipment location, and the number of indoor units." },
      { question: "Do mini splits provide heating too?", answer: "Many mini split systems are heat pumps that provide both cooling and heating. Cool Fox can explain which equipment fits the room and your comfort goals." },
      { question: "How many indoor units will I need?", answer: "That depends on the size, layout, insulation, sun exposure, and how the spaces connect. A room assessment helps determine whether one indoor unit or a multi-zone system makes sense." },
      { question: "Do mini splits need maintenance?", answer: "Yes. Filters, indoor coils, drain lines, outdoor equipment, and operating performance should be checked regularly to support airflow and efficiency." },
    ],
    relatedServices: ["ac-installation", "residential-hvac", "maintenance-plans"],
    icon: "unit",
  },
  {
    slug: "maintenance-plans",
    title: "HVAC Maintenance Plans",
    shortTitle: "Maintenance Plans",
    summary: "Routine care that helps reduce surprises and protect system performance.",
    description: "Arizona equipment works hard. Planned inspections help catch developing problems, support efficiency, and prepare your system for the season ahead.",
    symptoms: ["System has not been serviced recently", "Cooling costs are increasing", "Airflow has declined", "Dust builds up quickly", "You want fewer surprise breakdowns"],
    inclusions: ["Heating and cooling inspection", "Electrical connection checks", "Coil and drain evaluation", "Filter and airflow review", "Written findings and recommendations"],
    process: standardProcess,
    faqs: [
      { question: "How often should an Arizona HVAC system be serviced?", answer: "Most systems benefit from professional service twice a year, once before peak cooling and once before heating season." },
      { question: "What does a maintenance visit include?", answer: "The technician inspects operation, electrical components, temperatures, airflow, drainage, and visible wear, then explains any findings." },
      { question: "How often should filters be replaced?", answer: "Many homes need a filter change every one to three months. Pets, dust, allergies, filter type, and system use can shorten that interval." },
      { question: "Does maintenance prevent every breakdown?", answer: "No service can prevent every failure, but regular inspections can identify many developing issues before they become larger problems." },
    ],
    relatedServices: ["ac-repair", "heating", "indoor-air-quality"],
    icon: "wrench",
  },
  {
    slug: "emergency-hvac",
    title: "24/7 Emergency HVAC Service",
    shortTitle: "Emergency HVAC",
    summary: "Responsive help when loss of heating or cooling cannot wait.",
    description: "A failed system can become a safety concern in extreme Arizona weather. Call Cool Fox any time for emergency HVAC assistance.",
    symptoms: ["Complete cooling failure in extreme heat", "Burning smell or electrical concern", "Active water leak", "Heating failure during cold weather", "System will not shut off"],
    inclusions: ["24/7 phone response", "Priority diagnosis", "Safety evaluation", "Clear repair options", "Temporary guidance when a part is unavailable"],
    process: standardProcess,
    faqs: [
      { question: "Is emergency service available?", answer: "Yes. Cool Fox provides 24/7 emergency HVAC service. Call directly so the team can assess urgency and availability." },
      { question: "What should I do if I smell burning?", answer: "Turn the system off if it is safe to do so and call for help. If you see smoke or fire, leave the property and contact emergency services first." },
      { question: "Can I submit an emergency request online?", answer: "You can, but calling is the fastest way to reach the team for an urgent loss of heating or cooling." },
      { question: "Will you explain the price before repair?", answer: "Yes. You will receive the available options and pricing before approved work begins." },
    ],
    relatedServices: ["ac-repair", "heating", "residential-hvac"],
    icon: "alert",
  },
  {
    slug: "residential-hvac",
    title: "Residential HVAC Services",
    shortTitle: "Residential HVAC",
    summary: "Complete heating, cooling, and air quality care for Arizona homes.",
    description: "From a single repair to a full comfort upgrade, Cool Fox helps homeowners make informed decisions for reliable year-round comfort.",
    symptoms: ["Rooms do not stay comfortable", "System runs constantly", "Indoor air feels dusty or stale", "Equipment needs frequent repairs", "You are planning a home comfort upgrade"],
    inclusions: ["Cooling and heating service", "System replacements", "Preventive maintenance", "Indoor air quality options", "Comfort and airflow troubleshooting"],
    process: standardProcess,
    faqs: [
      { question: "What residential systems do you service?", answer: "Cool Fox works on common central air conditioners, heat pumps, furnaces, packaged systems, and related comfort equipment." },
      { question: "Can you help with uneven cooling?", answer: "Yes. Uneven temperatures can come from airflow, duct, equipment, insulation, or control issues. We inspect the system before recommending a solution." },
      { question: "Do you provide free quotes?", answer: "Free quotes are available. Call or send a request with details about the service you need." },
      { question: "Do you serve homes outside Phoenix?", answer: "Yes. Cool Fox serves communities across the Valley and parts of Northern Arizona. Check the service areas page for the current list." },
    ],
    relatedServices: ["ac-repair", "ac-installation", "mini-split-installation"],
    icon: "home",
  },
  {
    slug: "commercial-hvac",
    title: "Commercial HVAC Services",
    shortTitle: "Commercial HVAC",
    summary: "Practical HVAC support for local businesses and commercial properties.",
    description: "Comfort problems disrupt customers, teams, and operations. Cool Fox provides responsive commercial diagnosis, repair, maintenance, and replacement guidance.",
    symptoms: ["Customer or staff areas are uncomfortable", "Rooftop equipment has stopped", "Energy use is rising", "Recurring service interruptions", "A replacement or maintenance plan is needed"],
    inclusions: ["Commercial system diagnosis", "Repair and replacement options", "Rooftop unit service", "Preventive maintenance planning", "Clear communication with the property contact"],
    process: standardProcess,
    faqs: [
      { question: "Does Cool Fox handle commercial systems?", answer: "Yes. Cool Fox provides service for common light commercial HVAC systems and can confirm equipment coverage when you schedule." },
      { question: "Can service be coordinated with a property manager?", answer: "Yes. Provide the site contact, access details, and approval process when requesting service." },
      { question: "Is emergency commercial service available?", answer: "Yes. Call for 24/7 emergency assistance and the current response window." },
      { question: "Can you create a maintenance plan for a property?", answer: "Yes. The scope can be based on equipment type, quantity, condition, and operational needs." },
    ],
    relatedServices: ["emergency-hvac", "maintenance-plans", "ac-installation"],
    icon: "building",
  },
  {
    slug: "indoor-air-quality",
    title: "Indoor Air Quality Solutions",
    shortTitle: "Indoor Air Quality",
    summary: "Cleaner, more comfortable indoor air for Arizona homes and businesses.",
    description: "Desert dust, allergens, and tightly closed homes can affect indoor comfort. We identify practical filtration and air quality improvements for your system.",
    symptoms: ["Excess dust", "Odors or stale air", "Allergy concerns", "Humidity discomfort", "Poor airflow", "Frequent filter loading"],
    inclusions: ["Filter and airflow assessment", "Duct and equipment review", "Filtration options", "Air cleaning and comfort recommendations", "Installation and performance check"],
    process: standardProcess,
    faqs: [
      { question: "What indoor air quality options help with Arizona dust?", answer: "A properly fitted filter, sealed return leaks, clean equipment, and appropriate whole-home filtration can all help. The best option depends on your system and goals." },
      { question: "Will a higher rated filter always be better?", answer: "Not always. A filter that is too restrictive can reduce airflow. The system and filter cabinet should be evaluated before changing filter type." },
      { question: "Can HVAC work reduce indoor odors?", answer: "Sometimes. Filtration, ventilation, drainage, coil cleanliness, and source control may all matter. We first look for the likely cause." },
      { question: "Can you help with allergy concerns?", answer: "We can review HVAC-related options that may reduce airborne particles, while avoiding medical claims or one-size-fits-all recommendations." },
    ],
    relatedServices: ["maintenance-plans", "residential-hvac", "ac-installation"],
    icon: "air",
  },
  {
    slug: "heating",
    title: "Heating Repair and Installation",
    shortTitle: "Heating",
    summary: "Reliable furnace and heat pump service for cool Arizona nights.",
    description: "When temperatures drop, Cool Fox provides careful heating diagnosis, repair, maintenance, and replacement guidance.",
    symptoms: ["No warm air", "System cycles frequently", "Unusual odor or noise", "Heat pump will not change modes", "Some rooms remain cold", "Heating costs have increased"],
    inclusions: ["Furnace and heat pump diagnosis", "Safety and electrical checks", "Repair options", "Heating maintenance", "Replacement consultation when needed"],
    process: standardProcess,
    faqs: [
      { question: "Do Arizona heating systems need annual service?", answer: "Yes. Annual heating service helps confirm safe operation, identify wear, and prepare the system before colder weather." },
      { question: "Why is my heat pump blowing cool air?", answer: "Heat pumps can feel cooler than furnaces during normal operation, but thermostat, refrigerant, reversing valve, or backup heat issues can also cause a problem." },
      { question: "Do you repair furnaces and heat pumps?", answer: "Yes. Cool Fox services common residential and light commercial heating equipment." },
      { question: "When should a heating system be replaced?", answer: "Replacement may make sense when reliability, safety, efficiency, parts availability, and repair cost no longer support continued repair." },
    ],
    relatedServices: ["maintenance-plans", "emergency-hvac", "residential-hvac"],
    icon: "flame",
  },
];

export function getService(slug: string) {
  return services.find((service) => service.slug === slug);
}
